export const ptInfos = {
  "personalTrainer": [
    {   
      "value":"firstName",
      "inputType":"Input",
      "maxLength":75,
      "required":true,
      "label":"First name",
      "type":"C",  
    },
    {   
      "value":"lastName",
      "inputType":"Input",
      "maxLength":75,
      "required":true,
      "label":"Last name",
      "type":"C",  
    },
    {   
      "value":"email",
      "inputType":"Input",
      "maxLength":100,
      "required":false,
      "label":"Email",
      "type":"C",  
    },
    {   
      "value":"phoneNumber",
      "inputType":"Input",
      "maxLength":25,
      "required":false,
      "label":"Phone number",
      "type":"C",  
    },
    {   
      "value":"languageCodes",
      "inputType":"Dropdown",
      "maxLength":75,
      "required":true,
      "label":"Spoken languages",
      "type":"C",  
    },
    {   
      "value":"description",
      "inputType":"Input",
      "maxLength":3500,
      "required":true,
      "label":"Description",
      "type":"C",  
    },

    {   
      "value":"shortDescription",
      "inputType":"Input",
      "maxLength":150,
      "required":true,
      "label":"Short description",
      "type":"C",  
    },
    {   
      "value":"facebookUserId",
      "inputType":"Input",
      "maxLength":100,
      "required":false,
      "label":"Facebook user id",
      "type":"C",  
    },
    {   
      "value":"instagramUserId",
      "inputType":"Input",
      "maxLength":100,
      "required":false,
      "label":"Instagram user id",
      "type":"C",  
    },
    {   
      "value":"twitterUserId",
      "inputType":"Input",
      "maxLength":100,
      "required":false,
      "label":"Facebook user id",
      "type":"C",  
    },
    {   
      "value":"youtubeUserId",
      "inputType":"Input",
      "maxLength":100,
      "required":false,
      "label":"Facebook user id",
      "type":"C",  
    },
    {   
      "value":"webPageUserId",
      "inputType":"Input",
      "maxLength":100,
      "required":false,
      "label":"Facebook user id",
      "type":"C",  
    },
  ]
}